version: '3.8'

services:
  springboot-app:
    image: mining-service 
    build:
      context: .
      dockerfile: ./mining-service/infrastructure/Dockerfile
    ports:
      - "8080:8080"
    networks:
      - springboot-network

  postgres:
    image: postgres
    environment:
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    networks:
      - springboot-network

  activemq:
    image: vromero/activemq-artemis:2.6.1
    environment:
      ENABLE_JMX_EXPORTER: "true"
      ARTEMIS_MIN_MEMORY: "1512M"
      ARTEMIS_MAX_MEMORY: "2000M"
      ARTEMIS_USERNAME: "artemis"
      ARTEMIS_PASSWORD: "artemis"
    ports:
      - "8161:8161"
      - "61616:61616"

networks:
  springboot-network:
