version: '3.8'

services:
  springboot-app:
    image: mining-service 
    build:
      context: .
      dockerfile: ./mining-service/infrastructure/Dockerfile
    ports:
      - "8080:8080"
    networks:
      - springboot-network

  postgres:
    image: postgres
    environment:
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    networks:
      - springboot-network

networks:
  springboot-network:
